# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EonpJe0FKbwrBaWxq5Pa8XOqiifxexhL
"""

import pandas as pd

df = pd.read_csv("co2-data.csv")

df.head()

df.info()

df.isnull().sum()

# Remove rows where country or year is missing
df.dropna(subset=["country", "year"], inplace=True)

# Fill all numeric missing values with the median
numeric_columns = df.select_dtypes(include="number").columns

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

# Check remaining missing values
df.isnull().sum()

print(df.describe())

latest = df["year"].max()
latest_df = df[df["year"] == latest]

print(latest_df.sort_values("co2", ascending=False)[["country", "co2"]].head(10))

print(df[["co2", "co2_per_capita", "population", "gdp"]].corr())
# ==========================================
# DATASET ANALYSIS
# ==========================================

# General Observations
# - This dataset provides information about CO2 emissions of different countries over several years.
# - The country column tells us which country the data belongs to.
# - The year column helps us compare how CO2 emissions have changed over time.
# - The population column shows the total population of each country.
# - The GDP column gives an idea about the country's economic growth.
# - The CO2 column represents the total amount of carbon dioxide released.
# - The CO2 per capita column shows the average CO2 emission per person.

# Relationship Between Features
# - Countries with larger populations usually have higher total CO2 emissions because more people use energy and resources.
# - A higher GDP often means more industries, transportation, and energy consumption, which can increase CO2 emissions.
# - CO2 per capita depends on both the total CO2 emissions and the population of the country.
# - By comparing these features, we can understand how economic growth and population influence environmental pollution.

# ==========================================
# SUMMARY
# ==========================================

# In this assignment, I worked with a sustainability dataset related to CO2 emissions.
# I imported the dataset using the Pandas library and explored it with functions like
# head(), info(), and describe() to understand its structure.
# Then, I checked for missing values and handled them by removing rows with missing
# country or year values and filling the remaining numeric missing values with the median.
# After cleaning the data, I studied the relationship between important features such as
# country, population, GDP, and CO2 emissions. I also identified the top CO2-emitting
# countries and checked the correlation between key numerical columns.
# Overall, this assignment helped me understand how to clean, analyze, and interpret
# a real-world sustainability dataset using Python.
